### ISSUE TITLE
v1.1.1 Official Release: Code Optimizations 

### ISSUE THREAD

**Issue by iAegiss** [Riverify/rikky-takeaway#11]
压缩包已经损坏了 可以重新补上一份嘛 感激不尽

**Comment by riverify** [comment]
![image](https://github.com/riverify/rikky-takeaway/assets/97610640/3f3c9b89-307c-4cbe-aa57-e3c610357a12)
两种格式的压缩包在我这都没有问题，是不是压缩软件的问题呢？建议直接git clone或者点主页Code，download zip下载
![image](https://github.com/riverify/rikky-takeaway/assets/97610640/ffbe5149-5355-4119-8829-9204334827ba)
或者我刚刚复制的链接🔗(https://codeload.github.com/riverify/rikky-takeaway/zip/refs/heads/main)

**Comment by iAegiss** [comment]
![微信截图_20240115103528](https://github.com/riverify/rikky-takeaway/assets/107640904/5ff2b923-12ce-4ef3-a359-79bdd0117b88)
不知道为什么会这样 很奇怪 就是点击链接下载的

**Comment by riverify** [comment]
你电脑装了git吗，试试打开git bash，输入`git clone https://github.com/riverify/rikky-takeaway.git` 或者用IntelliJ IDEA的get from version control
<img width="405" alt="image" src="https://github.com/riverify/rikky-takeaway/assets/97610640/5b70029d-5a99-49fa-90fc-f8869a7586ad">
<img width="599" alt="image" src="https://github.com/riverify/rikky-takeaway/assets/97610640/ec2d0980-982a-4052-928b-15476a06263a">

**Comment by iAegiss** [comment]
okk 能克隆上了 能冒昧问下能加个联系方式嘛

**Comment by riverify** [comment]
CryingRiver@foxmail.com，我的邮箱
